export PYTHONPATH="/home/carla/MyProjects/SLP-FE-Linguistics/PT-G2S:/home/carla/.pycharm_helpers/pydev:/home/carla/MyProjects/SLP-FE-Linguistics:/home/carla/.pycharm_helpers/pycharm_display:/home/carla/.pycharm_helpers/third_party/thriftpy:/home/carla/.pycharm_helpers/pydev:/Users/CarlaViegas/Library/Caches/JetBrains/PyCharm2020.1/cythonExtensions:/home/carla/MyProjects/SLP-FE-Linguistics/PT-G2S:/home/carla/.local/share/virtualenvs/ProgressiveTransformersSLP-f7T2SrO1/lib/python37.zip:/home/carla/.local/share/virtualenvs/ProgressiveTransformersSLP-f7T2SrO1/lib/python3.7:/home/carla/.local/share/virtualenvs/ProgressiveTransformersSLP-f7T2SrO1/lib/python3.7/lib-dynload:/usr/lib/python3.7:/home/carla/.local/share/virtualenvs/ProgressiveTransformersSLP-f7T2SrO1/lib/python3.7/site-packages:/home/carla/.pycharm_helpers/pycharm_matplotlib_backend:/home/carla/.local/share/virtualenvs/ProgressiveTransformersSLP-f7T2SrO1/lib/python3.7/site-packages/IPython/extensions:/home/carla/MyProjects/SLP-FE-Linguistics/SLT"
#python ~/MyProjects/SLP-FE-Linguistics/PT-T2S/__main__.py train ~/MyProjects/SLP-FE-Linguistics/PT-T2S/Configs/handsbody.yaml 
#python ~/MyProjects/SLP-FE-Linguistics/PT-TG2S/__main__.py train ~/MyProjects/SLP-FE-Linguistics/PT-TG2S/Configs/handsbodyface3D.yaml
#python ~/MyProjects/SLP-FE-Linguistics/PT-TG2S/__main__.py train ~/MyProjects/SLP-FE-Linguistics/PT-TG2S/Configs/handsbodyface3Dauc.yaml
#python ~/MyProjects/SLP-FE-Linguistics/PT-TG2S/__main__.py train ~/MyProjects/SLP-FE-Linguistics/PT-TG2S/Configs/handsbody.yaml
#python ~/MyProjects/SLP-FE-Linguistics/PT-TG2S/__main__.py train ~/MyProjects/SLP-FE-Linguistics/PT-TG2S/Configs/handsbodyface2D.yaml --ckpt ~/MyProjects/SLP-FE-Linguistics/PT-TG2S/Models/handsbodyface2D/train1/410000_every.ckpt
#python ~/MyProjects/SLP-FE-Linguistics/PT-TG2S/__main__.py train ~/MyProjects/SLP-FE-Linguistics/PT-TG2S/Configs/handsbody.yaml --ckpt ~/MyProjects/SLP-FE-Linguistics/PT-TG2S/Models/handsbody/train1/best.ckpt
#python ~/MyProjects/SLP-FE-Linguistics/PT-TG2S/__main__.py train ~/MyProjects/SLP-FE-Linguistics/PT-TG2S/Configs/handsbody.yaml --ckpt ~/MyProjects/SLP-FE-Linguistics/PT-TG2S/Models/handsbody/train1/330000_every.ckpt
#python ~/MyProjects/SLP-FE-Linguistics/PT-TG2S/__main__.py train ~/MyProjects/SLP-FE-Linguistics/PT-TG2S/Configs/handsbodyface2D.yaml --ckpt ~/MyProjects/SLP-FE-Linguistics/PT-TG2S/Models/handsbodyface2D/train1/180000_every.ckpt
#python ~/MyProjects/SLP-FE-Linguistics/PT-TG2S/__main__.py test ~/MyProjects/SLP-FE-Linguistics/PT-TG2S/Configs/handsbodyface2D.yaml --ckpt ~/MyProjects/SLP-FE-Linguistics/PT-TG2S/Models/handsbodyface2D/210000_every.ckpt
python ~/MyProjects/SLP-FE-Linguistics/PT-TG2S/__main__.py test ~/MyProjects/SLP-FE-Linguistics/PT-TG2S/Configs/handsbodyface3Dauc.yaml --ckpt ~/MyProjects/SLP-FE-Linguistics/PT-TG2S/Models/handsbodyface3Dauc/train1/450000_every.ckpt
